### ISSUE TITLE
Including OpenPose face & hands keypoints

### ISSUE THREAD

**Issue by jaygit123** [KevinLTT/video2bvh#12]
Hi @KevinLTT ,
Thanks for the code. Works well. 

With respect to OpenPose face & hand keypoints, since you are using SMPL model (which does not consider face & hand keypoints) to generate the mesh model and also as you are selecting specific 3D keypoints to write to csv file, I don't think resultant bvh will have facial expression & hand motions. Correct me if I am wrong. (I tried and didn't work)
Also, let me know which all files have to be updated to enable facial expressions & hands motions in the output bvh. 

Thanks.

**Comment by jaygit123** [comment]
@KevinLTT could you help with the above request please?

**Comment by KevinLTT** [comment]
Hi @jaygit123 ,
Sorry for replying late. You are right, this project does not support facial expression and hand motions. Since the model are trained for estimating only 3D position of body joint, it does not support output face and hand 3D position. For 3D hand pose estimation, you can refer to [awesome-hand-pose-estimation](https://github.com/xinghaochen/awesome-hand-pose-estimation). As for facial expession, I'm not familiar with this filed.

**Comment by jaygit123** [comment]
Hi @KevinLTT ,
Thanks for the update and input.
